name: Promote Twilio Studio Flow

permissions:
  contents: write
  issues: write

on:
  workflow_dispatch:
    inputs:
      flow_name:
        description: "Folder name of the flow under .studio/ (e.g. order-bot)"
        required: true
      from_env:
        description: "Source environment (e.g. stage)"
        required: true
        default: "stage"
      to_env:
        description: "Target environment (e.g. prod)"
        required: true
        default: "prod"
      from_flow_sid:
        description: "Source Flow SID"
        required: true
      to_flow_sid:
        description: "Target Flow SID"
        required: true
      commit_message:
        description: "Promotion message"
        required: true
        default: "Promote to prod"
      replace_function_urls:
        description: "Should function URLs be rewritten to match the target environment?"
        required: true
        default: "true"
      require_approval:
        description: "Require manual approval before promoting?"
        required: true
        default: "false"

jobs:
  promote:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.require_approval == 'true' && 'production' || '' }}

    env:
      ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}

    steps:
      - name: Require approval before proceeding (optional)
        if: ${{ github.event.inputs.require_approval == 'true' }}
        run: echo "✅ Manual approval granted for '${{ github.event.inputs.flow_name }}'. Proceeding with promotion..."

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - name: Fetch Studio Flow from Source
        run: |
          mkdir -p .studio/${{ github.event.inputs.flow_name }}

          curl -s -f -u "$ACCOUNT_SID:$AUTH_TOKEN" \
            "https://studio.twilio.com/v2/Flows/${{ github.event.inputs.from_flow_sid }}" \
            -o .studio/${{ github.event.inputs.flow_name }}/from-full.json

          jq '.definition' .studio/${{ github.event.inputs.flow_name }}/from-full.json > \
            .studio/${{ github.event.inputs.flow_name }}/from-definition.json

      - name: Rewrite Function URLs (if enabled)
        if: ${{ github.event.inputs.replace_function_urls == 'true' }}
        run: |
          FROM_ENV="${{ github.event.inputs.from_env }}"
          TO_ENV="${{ github.event.inputs.to_env }}"
          FLOW_PATH=".studio/${{ github.event.inputs.flow_name }}"

          echo "🔄 Rewriting Function URLs from '${FROM_ENV}' to '${TO_ENV}'..."
          sed -E "s#https://([a-zA-Z0-9-]+)-${FROM_ENV}\.twil\.io#https://\1-${TO_ENV}.twil.io#g" \
            "$FLOW_PATH/from-definition.json" > "$FLOW_PATH/promoted-definition.json"

      - name: Copy definition without rewriting (if URL replacement is off)
        if: ${{ github.event.inputs.replace_function_urls == 'false' }}
        run: |
          cp .studio/${{ github.event.inputs.flow_name }}/from-definition.json \
            .studio/${{ github.event.inputs.flow_name }}/promoted-definition.json

      - name: Set up Git credentials
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Commit Definition (optional for audit)
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'

          git add .studio/${{ github.event.inputs.flow_name }}/promoted-definition.json
          git commit -m "Promote ${{ github.event.inputs.flow_name }}: ${{ github.event.inputs.commit_message }}" || echo "Nothing to commit"
          git push || echo "Nothing to push"

      - name: Promote to Target Flow
        run: |
          echo "Promoting flow '${{ github.event.inputs.flow_name }}' to '${{ github.event.inputs.to_env }}'..."

          DEFINITION=$(jq -c . .studio/${{ github.event.inputs.flow_name }}/promoted-definition.json)

          HTTP_STATUS=$(curl -s -o response.json -w "%{http_code}" -X POST \
            "https://studio.twilio.com/v2/Flows/${{ github.event.inputs.to_flow_sid }}" \
            -u "$ACCOUNT_SID:$AUTH_TOKEN" \
            --data-urlencode "Definition=$DEFINITION" \
            --data-urlencode "Status=published" \
            --data-urlencode "CommitMessage=${{ github.event.inputs.commit_message }}")

          if [[ "$HTTP_STATUS" != "200" ]]; then
            echo "❌ Flow promotion failed (HTTP $HTTP_STATUS)"
            echo "Response:"
            cat response.json
            exit 1
          fi

          echo "✅ Successfully promoted '${{ github.event.inputs.flow_name }}' to '${{ github.event.inputs.to_env }}'."
